upd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -97,13 +97,27 @@ jobs:
           port: 22
           script: |
             echo "Running health check..."
+            
             if ! docker ps | grep -q app; then
               echo "Starting stopped container: app"
               docker start app
-              fi
-            docker exec app java -cp /app/out com.Main --health-check
-           
-
+              for i in {1..10}; do
+                if docker ps | grep -q app; then
+                  echo "Container is now running."
+                  break
+                fi
+                echo "Waiting for container to start..."
+                sleep 1
+              done
+            fi
+            
+            if docker ps | grep -q app; then
+              docker exec app java -cp /app/out com.Main --health-check
+            else 
+              echo "Container failed to start"
+              exit 1
+            fi
+            
       - name: Rollback if health check fails
         if: failure()
         uses: appleboy/ssh-action@v0.1.6
